name: Build & Release Spent Android

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_NUMBER: ${{ github.run_number }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Android Debug APK
      run: ./gradlew :app:assembleDebug

    - name: Upload Android Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: spent-android-debug-apk
        path: app/build/outputs/apk/debug/*.apk

    - name: Build Release App Bundle (.aab)
      run: ./gradlew :app:bundleRelease --stacktrace

    - name: Upload Release App Bundle (.aab)
      uses: actions/upload-artifact@v4
      with:
        name: spent-release-bundle
        path: app/build/outputs/bundle/release/*.aab
